doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                profiling_collect_backtrace: '%kernel.debug%'
            audit:
                url: '%env(resolve:AUDIT_DATABASE_URL)%'
                profiling_collect_backtrace: '%kernel.debug%'
    orm:
        default_entity_manager: default
        controller_resolver:
            auto_mapping: false
        entity_managers:
            default:
                connection: default
                validate_xml_mapping: true
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true
                mappings:
                    App:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Domain/Entity'
                        prefix: 'App\Domain\Entity'
                        alias: App
            audit:
                connection: audit
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware

when@test:
    doctrine:
        dbal:
            connections:
                default:
                    dbname_suffix: '_test%env(default::TEST_TOKEN)%'
                audit:
                    dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            entity_managers:
                default:
                    query_cache_driver:
                        type: pool
                        pool: doctrine.system_cache_pool
                    result_cache_driver:
                        type: pool
                        pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
